def error(e: Exception):
  print(e)
  exit(1)
